# Generated by Django 5.2.3 on 2025-11-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_budget_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProcessingJob',
        ),
    ]
